src/Models/Player/PlayerProfileViewModel.cs
namespace lol.Models.Player
{
    public class PlayerProfileViewModel
    {
        public string Username { get; set; }        
        public int ProfileIconId { get; set; }
        public long Level { get; set; }
    }
}

src/Models/Player/SelectPlayerViewModel.cs
using RiotSharp.Misc;

namespace lol.Models.Player
{
    public class SelectPlayerViewModel
    {
        public string Username { get; set; }
        public Region Region { get; set; } = Region.na;
    }
}

src/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RiotSharp;
using RiotSharp.Interfaces;
using RiotSharp.Misc;

namespace lol.Controllers
{
    public class HomeController : Controller
    {
        public IRiotApi RiotApi { get; set; }
        public HomeController(IRiotApi riotApi)
        {
            RiotApi = riotApi ?? throw new ArgumentNullException(nameof(riotApi));
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Champion()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }
        public async Task<IActionResult> Lol()
        {
            ViewData["Message"] = "League of Legends";

            var x = await RiotApi.GetSummonerByNameAsync(
                Region.na, 
                "mattt90");
            return View();
        }
        
        public IActionResult Statistics()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using lol.Models.Player;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using RiotSharp;
using RiotSharp.Interfaces;
using RiotSharp.Misc;

namespace lol.Controllers
{
    public class PlayerController : Controller
    {
        public IRiotApi RiotApi { get; }
        private IMemoryCache Cache { get; }
        public PlayerController(
            IMemoryCache memoryCache, 
            IRiotApi riotApi)
        {
            RiotApi = riotApi ?? throw new ArgumentNullException(nameof(riotApi));
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> SelectPlayer(SelectPlayerViewModel selectPlayerViewModel)
        {
            ViewData["Message"] = "League of Legends";

            var summoner = await RiotApi.GetSummonerByNameAsync(
                selectPlayerViewModel.Region, 
                selectPlayerViewModel.Username);

            var matchList = await RiotApi.GetMatchListAsync(
                selectPlayerViewModel.Region,
                summoner.AccountId,
                beginIndex: 0,
                endIndex: 1);

            var match = await RiotApi.GetMatchAsync(
                selectPlayerViewModel.Region,
                matchList.Matches[0].GameId);

            return View(new PlayerProfileViewModel
            {
                Username = summoner.Name,
                Level = summoner.Level,
                ProfileIconId = summoner.ProfileIconId
            });
        }
    }
}

src/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/Views/Home/Champion.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/Views/Home/Index.cshtml
@using lol.Models.Player;
@model SelectPlayerViewModel

@{
    ViewData["Title"] = "Home Page";
}

<form asp-controller="Player" asp-action="SelectPlayer" method="get">
    Username:  <input asp-for="Username" /> <br />
    <button type="submit">Find</button>
</form>

src/Views/Home/Lol.cshtml
@{
    ViewData["Title"] = "Lol";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Lol</p>

src/Views/Home/Statistics.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/Views/Player/Index.cshtml
@using lol.Models.Player;
@model SelectPlayerViewModel

@{
    ViewData["Title"] = "Player Information Page";
}

<form asp-action="SelectPlayer" method="get">
    Username:  <input asp-for="Username" /> <br />
    <button type="submit">Find</button>
</form>

src/Views/Player/SelectPlayer.cshtml
@{
    ViewData["Title"] = "Player Information Page";
}

<div>
    <h1>@Model.Username</h1>
    <p>Level: @Model.Level</p>
</div>

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lol</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">lol</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>                    
                    <li><a asp-area="" asp-controller="Home" asp-action="Champion">Champion</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Statistics">Stats</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - lol</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>